/*
  EASY QUESTION BANK — MASKS OF TIME / EMPTY SHELL
  Loaded by index.html. Do not rename EASY_QUESTIONS.
*/
var EASY_QUESTIONS = [
  {q:"What game features Mario rescuing Princess Peach?",a:["Sonic the Hedgehog","Super Mario Bros.","Minecraft","Pac-Man"],c:1,cat:"GAMING",tier:"documented"},
  {q:"Which game series features the character Pikachu?",a:["Pokemon","Zelda","Fortnite","Halo"],c:0,cat:"GAMING",tier:"documented"},
  {q:"What color is Sonic the Hedgehog?",a:["Red","Green","Blue","Yellow"],c:2,cat:"GAMING",tier:"documented"},
  {q:"Which game is built from blocks and lets players mine resources?",a:["Minecraft","Tetris","FIFA","Overwatch"],c:0,cat:"GAMING",tier:"documented"},
  {q:"What does the A button usually do in a video game menu?",a:["Confirms a selection","Turns off the console","Deletes the game","Opens a browser"],c:0,cat:"GAMING",tier:"documented"},
  {q:"Which Nintendo character wears green and carries a sword?",a:["Luigi","Link","Kirby","Donkey Kong"],c:1,cat:"GAMING",tier:"documented"},
  {q:"Pac-Man is known for eating what?",a:["Coins","Dots","Apples","Cards"],c:1,cat:"GAMING",tier:"documented"},
  {q:"Which game uses falling blocks that players arrange into lines?",a:["Tetris","Fortnite","Roblox","Animal Crossing"],c:0,cat:"GAMING",tier:"documented"},
  {q:"What is the name of Mario's brother?",a:["Wario","Luigi","Yoshi","Bowser"],c:1,cat:"GAMING",tier:"documented"},
  {q:"Which game is famous for the phrase 'Victory Royale'?",a:["Fortnite","Call of Duty","Pokemon","Tetris"],c:0,cat:"GAMING",tier:"documented"},
  {q:"What is the main enemy called in Super Mario games?",a:["Bowser","Ganondorf","Dr. Eggman","Mewtwo"],c:0,cat:"GAMING",tier:"documented"},
  {q:"Which company makes the PlayStation?",a:["Nintendo","Microsoft","Sony","Sega"],c:2,cat:"GAMING",tier:"documented"},
  {q:"Which company makes the Xbox?",a:["Apple","Microsoft","Nintendo","Sony"],c:1,cat:"GAMING",tier:"documented"},
  {q:"What does a controller's D-pad usually control?",a:["Direction","Sound volume","Internet speed","Battery charge"],c:0,cat:"GAMING",tier:"documented"},
  {q:"Which game series includes Master Chief?",a:["Halo","Fallout","Resident Evil","Final Fantasy"],c:0,cat:"GAMING",tier:"documented"},
  {q:"What kind of creature is Pikachu?",a:["Electric mouse","Fire dragon","Water turtle","Rock monster"],c:0,cat:"GAMING",tier:"documented"},
  {q:"Which game console is portable and made by Nintendo?",a:["Nintendo Switch","PlayStation 5","Xbox Series X","Dreamcast"],c:0,cat:"GAMING",tier:"documented"},
  {q:"What does 'multiplayer' mean?",a:["More than one person can play","The game has many levels","The game is expensive","The game is unfinished"],c:0,cat:"GAMING",tier:"documented"},
  {q:"Which game character is a yellow circle with a mouth?",a:["Pac-Man","Kirby","Sonic","Crash"],c:0,cat:"GAMING",tier:"documented"},
  {q:"What do you collect in many Mario levels?",a:["Rings","Coins","Cards","Stars only"],c:1,cat:"GAMING",tier:"documented"},
  {q:"Which game lets players build and survive on an island with animal neighbors?",a:["Animal Crossing","Doom","Tetris","Street Fighter"],c:0,cat:"GAMING",tier:"documented"},
  {q:"What is the name of the green dinosaur in Mario games?",a:["Yoshi","Toad","Waluigi","Kirby"],c:0,cat:"GAMING",tier:"documented"},
  {q:"Which arcade game has ghosts named Blinky, Pinky, Inky and Clyde?",a:["Pac-Man","Space Invaders","Asteroids","Donkey Kong"],c:0,cat:"GAMING",tier:"documented"},
  {q:"What is a 'save file' used for?",a:["Keeping game progress","Changing the soundtrack","Cleaning a console","Buying a game"],c:0,cat:"GAMING",tier:"documented"},
  {q:"Which game features a battle royale island and building walls?",a:["Fortnite","The Sims","Mario Kart","Tetris"],c:0,cat:"GAMING",tier:"documented"},
  {q:"Which game franchise has a character named Princess Zelda?",a:["The Legend of Zelda","Pokemon","Sonic","Metal Gear"],c:0,cat:"GAMING",tier:"documented"},
  {q:"What are the enemies in Minecraft that explode called?",a:["Creepers","Goombas","Ghosts","Raiders"],c:0,cat:"GAMING",tier:"documented"},
  {q:"Which racing series features blue shells and bananas?",a:["Mario Kart","Gran Turismo","Forza","Need for Speed"],c:0,cat:"GAMING",tier:"documented"},
  {q:"Which classic game has a character climb ladders to rescue someone from a gorilla?",a:["Donkey Kong","Galaga","Pong","Tetris"],c:0,cat:"GAMING",tier:"documented"},
  {q:"What is a 'boss' in a video game?",a:["A powerful enemy","The main menu","A type of controller","A save point"],c:0,cat:"GAMING",tier:"documented"},
  {q:"Which artist sang 'Thriller'?",a:["Michael Jackson","Prince","Elvis Presley","David Bowie"],c:0,cat:"MUSIC",tier:"documented"},
  {q:"Which band sang 'Hey Jude'?",a:["The Beatles","The Rolling Stones","Queen","ABBA"],c:0,cat:"MUSIC",tier:"documented"},
  {q:"What instrument has black and white keys?",a:["Piano","Trumpet","Drum","Violin"],c:0,cat:"MUSIC",tier:"documented"},
  {q:"Which artist is known as the King of Pop?",a:["Michael Jackson","Elvis Presley","Prince","Drake"],c:0,cat:"MUSIC",tier:"documented"},
  {q:"Which singer performed 'Rolling in the Deep'?",a:["Adele","Beyonce","Rihanna","Lady Gaga"],c:0,cat:"MUSIC",tier:"documented"},
  {q:"Which band performed 'Bohemian Rhapsody'?",a:["Queen","The Beatles","Nirvana","U2"],c:0,cat:"MUSIC",tier:"documented"},
  {q:"What does a DJ usually play?",a:["Recorded music","Only drums","Sports highlights","Movies"],c:0,cat:"MUSIC",tier:"documented"},
  {q:"Which instrument usually has six strings?",a:["Guitar","Piano","Trumpet","Flute"],c:0,cat:"MUSIC",tier:"documented"},
  {q:"What is the name of a singer performing alone?",a:["Solo artist","Orchestra","Choir","Duo"],c:0,cat:"MUSIC",tier:"documented"},
  {q:"Which artist sang 'Shake It Off'?",a:["Taylor Swift","Ariana Grande","Billie Eilish","Katy Perry"],c:0,cat:"MUSIC",tier:"documented"},
  {q:"Which band featured John Lennon and Paul McCartney?",a:["The Beatles","The Who","The Kinks","The Beach Boys"],c:0,cat:"MUSIC",tier:"documented"},
  {q:"What music format came after cassette tapes for many listeners?",a:["Compact disc","Wax cylinder","8-track only","Sheet music"],c:0,cat:"MUSIC",tier:"documented"},
  {q:"Which singer was known as the King of Rock and Roll?",a:["Elvis Presley","Frank Sinatra","Bob Dylan","Prince"],c:0,cat:"MUSIC",tier:"documented"},
  {q:"What does a microphone turn into an electrical signal?",a:["Sound","Light","Heat","Water"],c:0,cat:"MUSIC",tier:"documented"},
  {q:"Which musician played guitar in Nirvana?",a:["Kurt Cobain","Dave Grohl","Eddie Vedder","Billy Corgan"],c:0,cat:"MUSIC",tier:"documented"},
  {q:"Which artist recorded 'Purple Rain'?",a:["Prince","David Bowie","Elton John","George Michael"],c:0,cat:"MUSIC",tier:"documented"},
  {q:"What is a band with four members called?",a:["Quartet","Trio","Duo","Orchestra"],c:0,cat:"MUSIC",tier:"documented"},
  {q:"Which instrument is played with drumsticks?",a:["Drums","Violin","Saxophone","Piano"],c:0,cat:"MUSIC",tier:"documented"},
  {q:"Which singer released the album '21'?",a:["Adele","Madonna","Beyonce","Sia"],c:0,cat:"MUSIC",tier:"documented"},
  {q:"Which band sang 'Smells Like Teen Spirit'?",a:["Nirvana","Radiohead","Oasis","Green Day"],c:0,cat:"MUSIC",tier:"documented"},
  {q:"Which TV family lives in Springfield?",a:["The Simpsons","The Griffins","The Belchers","The Bluths"],c:0,cat:"TV",tier:"documented"},
  {q:"Who lives in a pineapple under the sea?",a:["SpongeBob SquarePants","Mickey Mouse","Bugs Bunny","Scooby-Doo"],c:0,cat:"TV",tier:"documented"},
  {q:"Which show features dragons and the Iron Throne?",a:["Game of Thrones","The Witcher","The Crown","Vikings"],c:0,cat:"TV",tier:"documented"},
  {q:"Which sitcom takes place in the office of Dunder Mifflin?",a:["The Office","Friends","Seinfeld","Cheers"],c:0,cat:"TV",tier:"documented"},
  {q:"Which show follows Walter White?",a:["Breaking Bad","Better Call Saul","Dexter","Ozark"],c:0,cat:"TV",tier:"documented"},
  {q:"Which animated show stars a talking baby named Stewie?",a:["Family Guy","The Simpsons","South Park","Rick and Morty"],c:0,cat:"TV",tier:"documented"},
  {q:"Which show has the theme song 'I'll Be There for You'?",a:["Friends","Seinfeld","Frasier","Cheers"],c:0,cat:"TV",tier:"documented"},
  {q:"Which TV doctor lives in a blue police box?",a:["Doctor Who","House","Grey","Quinn"],c:0,cat:"TV",tier:"documented"},
  {q:"What is the name of the yellow cartoon father in The Simpsons?",a:["Homer","Bart","Ned","Moe"],c:0,cat:"TV",tier:"documented"},
  {q:"Which streaming series follows a strange girl called Eleven?",a:["Stranger Things","Wednesday","Dark","The OA"],c:0,cat:"TV",tier:"documented"},
  {q:"Which series features the characters Ross, Rachel and Joey?",a:["Friends","The Office","How I Met Your Mother","New Girl"],c:0,cat:"TV",tier:"documented"},
  {q:"Which cartoon dog says 'Scooby-Dooby-Doo'?",a:["Scooby-Doo","Brian","Santa's Little Helper","Courage"],c:0,cat:"TV",tier:"documented"},
  {q:"Which show stars an animated scientist named Rick?",a:["Rick and Morty","Futurama","The Simpsons","Archer"],c:0,cat:"TV",tier:"documented"},
  {q:"What does a TV remote control?",a:["Television functions","The internet","The weather","A game save"],c:0,cat:"TV",tier:"documented"},
  {q:"Which show has contestants answer questions for money?",a:["Who Wants to Be a Millionaire?","Friends","The Office","Breaking Bad"],c:0,cat:"TV",tier:"documented"},
  {q:"Who played Harry Potter in the film series?",a:["Daniel Radcliffe","Elijah Wood","Tom Holland","Robert Pattinson"],c:0,cat:"FILM",tier:"documented"},
  {q:"Which film features a ship called the Titanic?",a:["Titanic","Jaws","Avatar","Frozen"],c:0,cat:"FILM",tier:"documented"},
  {q:"What color are the pills in The Matrix?",a:["Red and blue","Green and yellow","Black and white","Orange and purple"],c:0,cat:"FILM",tier:"documented"},
  {q:"Which film features a shark attacking beachgoers?",a:["Jaws","Alien","The Meg","Titanic"],c:0,cat:"FILM",tier:"documented"},
  {q:"Which film series features Darth Vader?",a:["Star Wars","Star Trek","Harry Potter","The Matrix"],c:0,cat:"FILM",tier:"documented"},
  {q:"What is the name of the ogre played by Mike Myers?",a:["Shrek","Fiona","Donkey","Gru"],c:0,cat:"FILM",tier:"documented"},
  {q:"Which superhero is Bruce Wayne?",a:["Batman","Superman","Spider-Man","Iron Man"],c:0,cat:"FILM",tier:"documented"},
  {q:"What does E.T. want to do in the famous line?",a:["Go home","Find treasure","Save the world","Become human"],c:0,cat:"FILM",tier:"documented"},
  {q:"Which film has a clown called Pennywise?",a:["It","Joker","The Mask","Saw"],c:0,cat:"FILM",tier:"documented"},
  {q:"Which movie features toys that come alive when people leave?",a:["Toy Story","Small Soldiers","Gremlins","The Lego Movie"],c:0,cat:"FILM",tier:"documented"},
  {q:"What is the name of the wizard school in Harry Potter?",a:["Hogwarts","Narnia","Mordor","Neverland"],c:0,cat:"FILM",tier:"documented"},
  {q:"Which actor played Iron Man in the Marvel films?",a:["Robert Downey Jr.","Chris Evans","Chris Hemsworth","Mark Ruffalo"],c:0,cat:"FILM",tier:"documented"},
  {q:"Which film features a yellow family called the Parrs?",a:["The Incredibles","Despicable Me","Minions","Up"],c:0,cat:"FILM",tier:"documented"},
  {q:"Which movie takes place in a theme park with cloned dinosaurs?",a:["Jurassic Park","King Kong","Godzilla","Avatar"],c:0,cat:"FILM",tier:"documented"},
  {q:"Who says 'I'll be back' in The Terminator?",a:["The Terminator","John Connor","Kyle Reese","Sarah Connor"],c:0,cat:"FILM",tier:"documented"},
  {q:"The Mandela Effect describes what?",a:["Widely shared false memories","A type of television","A legal case","A musical genre"],c:0,cat:"POP",tier:"disputed"},
  {q:"What is a conspiracy theory?",a:["A claim of a hidden plot","A confirmed law","A science experiment","A movie review"],c:0,cat:"POP",tier:"documented"},
  {q:"What does UFO traditionally stand for?",a:["Unidentified Flying Object","United Flight Office","Universal Film Order","Unknown Frequency Output"],c:0,cat:"POP",tier:"documented"},
  {q:"What does 'viral' mean online?",a:["Spreading quickly","Being illegal","Being secret","Being deleted"],c:0,cat:"POP",tier:"documented"},
  {q:"What is an urban legend?",a:["A modern story passed around as true","A city law","A historical document","A building"],c:0,cat:"POP",tier:"documented"},
  {q:"What does 'fake news' describe?",a:["False or misleading material presented as news","A comedy show","Weather reporting","A newspaper layout"],c:0,cat:"POP",tier:"documented"},
  {q:"What is a meme?",a:["An idea or image copied and shared online","A computer virus","A radio antenna","A secret code"],c:0,cat:"POP",tier:"documented"},
  {q:"What is a spoiler?",a:["Information that reveals a story surprise","A broken television","A movie poster","A false clue"],c:0,cat:"POP",tier:"documented"},
  {q:"What is an eyewitness?",a:["Someone who saw an event","A police officer","A reporter","A judge"],c:0,cat:"POP",tier:"documented"},
  {q:"What does 'going down a rabbit hole' mean online?",a:["Following a subject into deeper links","Leaving a website","Playing a game","Erasing history"],c:0,cat:"POP",tier:"documented"},
  {q:"What does CIA stand for?",a:["Central Intelligence Agency","Civil Investigation Agency","Central Internet Authority","Counter Intelligence Army"],c:0,cat:"CIA",tier:"documented"},
  {q:"What does FBI stand for?",a:["Federal Bureau of Investigation","Foreign Bureau of Intelligence","Federal Bank of Information","First Bureau of Inquiry"],c:0,cat:"CIA",tier:"documented"},
  {q:"What does NSA stand for?",a:["National Security Agency","National Space Administration","New States Agency","North Signal Authority"],c:0,cat:"CIA",tier:"documented"},
  {q:"What does 'classified' mean?",a:["Officially restricted from public release","Proven false","Available everywhere","A type of book"],c:0,cat:"CIA",tier:"documented"},
  {q:"What does a spy usually try to collect?",a:["Information","Rainwater","Artwork","Votes"],c:0,cat:"CIA",tier:"documented"},
  {q:"What is surveillance?",a:["Watching or monitoring people or places","Writing a story","Building a radio","Voting"],c:0,cat:"CIA",tier:"documented"},
  {q:"What is a code name?",a:["A secret name for a person or operation","A computer password only","A legal name","A radio song"],c:0,cat:"CIA",tier:"documented"},
  {q:"What is a whistleblower?",a:["A person who exposes wrongdoing","A referee","A singer","A police officer"],c:0,cat:"CIA",tier:"documented"},
  {q:"Which country is home to the pyramids of Giza?",a:["Egypt","Greece","Italy","Mexico"],c:0,cat:"ANCIENT",tier:"documented"},
  {q:"Which ancient civilization built the Colosseum?",a:["Romans","Vikings","Aztecs","Maya"],c:0,cat:"ANCIENT",tier:"documented"},
  {q:"Which ancient structure is in Athens, Greece?",a:["The Parthenon","The Colosseum","Stonehenge","The Sphinx"],c:0,cat:"ANCIENT",tier:"documented"},
  {q:"What were Egyptian pyramids primarily built as?",a:["Tombs","Schools","Factories","Theatres"],c:0,cat:"ANCIENT",tier:"documented"},
  {q:"What is a mummy?",a:["A preserved dead body","A monster","A pyramid","A king"],c:0,cat:"ANCIENT",tier:"documented"},
  {q:"Which city was buried by Mount Vesuvius?",a:["Pompeii","Rome","Athens","Cairo"],c:0,cat:"ANCIENT",tier:"documented"},
  {q:"What is Stonehenge made from?",a:["Large stones","Wood","Glass","Metal"],c:0,cat:"ANCIENT",tier:"documented"},
  {q:"Which ancient people are associated with Rome?",a:["Romans","Incas","Maya","Vikings"],c:0,cat:"ANCIENT",tier:"documented"},
  {q:"What did ancient Egyptians write on?",a:["Papyrus","Plastic","Screens","Newspapers"],c:0,cat:"ANCIENT",tier:"documented"},
  {q:"Which ancient civilization built Machu Picchu?",a:["Inca","Roman","Greek","Egyptian"],c:0,cat:"ANCIENT",tier:"documented"},
  {q:"What currency is used in the United States?",a:["Dollar","Pound","Euro","Yen"],c:0,cat:"MONEY",tier:"documented"},
  {q:"What does ATM stand for?",a:["Automated Teller Machine","Any Time Money","Automatic Trade Market","American Transfer Method"],c:0,cat:"MONEY",tier:"documented"},
  {q:"What is a budget?",a:["A plan for spending money","A bank building","A type of coin","A tax form"],c:0,cat:"MONEY",tier:"documented"},
  {q:"What does saving money mean?",a:["Keeping some for later","Spending more","Borrowing money","Printing cash"],c:0,cat:"MONEY",tier:"documented"},
  {q:"What is interest at a bank?",a:["Money earned or charged over time","A type of card","A coin","A salary"],c:0,cat:"MONEY",tier:"documented"},
  {q:"What is a loan?",a:["Money borrowed that must be repaid","Free money","A tax","A receipt"],c:0,cat:"MONEY",tier:"documented"},
  {q:"What is a receipt?",a:["Proof of a purchase","A bank account","A type of loan","A stock"],c:0,cat:"MONEY",tier:"documented"},
  {q:"What is a credit card used for?",a:["Making purchases with borrowed money","Growing food","Listening to music","Opening a door"],c:0,cat:"MONEY",tier:"documented"},
  {q:"What does 'profit' mean?",a:["Money left after costs","A type of tax","A debt","A receipt"],c:0,cat:"MONEY",tier:"documented"},
  {q:"What is a bank?",a:["A place that manages money","A government building","A music venue","A school"],c:0,cat:"MONEY",tier:"documented"},
  {q:"What is a secret society?",a:["A group with private membership or rituals","A public park","A government office","A sports team"],c:0,cat:"SOCIETIES",tier:"documented"},
  {q:"Which university is Skull and Bones associated with?",a:["Yale","Harvard","Oxford","MIT"],c:0,cat:"SOCIETIES",tier:"documented"},
  {q:"What symbol is strongly associated with Freemasonry?",a:["Square and compasses","A red cross","A crown","A lightning bolt"],c:0,cat:"SOCIETIES",tier:"documented"},
  {q:"What is an initiation?",a:["A ceremony for joining a group","A court trial","A radio signal","A type of vote"],c:0,cat:"SOCIETIES",tier:"documented"},
  {q:"Which group is a real historical secret society founded in 1776?",a:["The Bavarian Illuminati","The Avengers","The Jedi Order","The Men in Black"],c:0,cat:"SOCIETIES",tier:"documented"},
  {q:"What is a password used for?",a:["Restricting access","Playing music","Making food","Buying land"],c:0,cat:"SOCIETIES",tier:"documented"},
  {q:"What does UFO traditionally stand for?",a:["Unidentified Flying Object","United Flight Office","Universal Film Order","Unknown Frequency Output"],c:0,cat:"ALIENS",tier:"documented"},
  {q:"What planet do humans live on?",a:["Earth","Mars","Venus","Jupiter"],c:0,cat:"ALIENS",tier:"documented"},
  {q:"Which planet is known as the Red Planet?",a:["Mars","Venus","Mercury","Neptune"],c:0,cat:"ALIENS",tier:"documented"},
  {q:"What does NASA study and explore?",a:["Space","The ocean only","Ancient Rome","Music"],c:0,cat:"ALIENS",tier:"documented"},
  {q:"What is Area 51 most associated with in popular culture?",a:["Aliens and secret aircraft","A sports team","A movie studio","A bank"],c:0,cat:"ALIENS",tier:"documented"},
  {q:"Which planet is famous for its rings?",a:["Saturn","Earth","Mars","Mercury"],c:0,cat:"ALIENS",tier:"documented"},
  {q:"What is an astronaut?",a:["A person trained to travel in space","A type of alien","A scientist only","A television host"],c:0,cat:"ALIENS",tier:"documented"},
  {q:"What is the Moon?",a:["Earth's natural satellite","A planet","A star","A comet"],c:0,cat:"ALIENS",tier:"documented"},
  {q:"What does a telescope help people see?",a:["Distant objects","Sound waves","Smells","Dreams"],c:0,cat:"ALIENS",tier:"documented"},
  {q:"What is a planet?",a:["A large body orbiting a star","A kind of radio","A secret group","A type of animal"],c:0,cat:"ALIENS",tier:"documented"},
  {q:"What is a bias?",a:["A tendency that affects judgement","A type of telescope","A secret code","A radio station"],c:0,cat:"MIND",tier:"documented"},
  {q:"What is a memory?",a:["Information recalled from the past","A kind of computer only","A physical object","A law"],c:0,cat:"MIND",tier:"documented"},
  {q:"What is an illusion?",a:["Something that appears different from reality","A proven fact","A type of bank","A television channel"],c:0,cat:"MIND",tier:"documented"},
  {q:"What does it mean to concentrate?",a:["Focus attention","Fall asleep","Forget everything","Tell a lie"],c:0,cat:"MIND",tier:"documented"},
  {q:"What is stress?",a:["A response to pressure or demand","A type of food","A TV programme","A currency"],c:0,cat:"MIND",tier:"documented"},
  {q:"What is a habit?",a:["A repeated behavior","A single accident","A secret","A kind of radio"],c:0,cat:"MIND",tier:"documented"},
  {q:"What does 'peer pressure' mean?",a:["Pressure from people around you","Pressure in the weather","A medical scan","A computer error"],c:0,cat:"MIND",tier:"documented"},
  {q:"What is an emotion?",a:["A feeling such as fear or joy","A machine","A building","A television signal"],c:0,cat:"MIND",tier:"documented"},
  {q:"What is a dream?",a:["An experience during sleep","A type of film","A financial plan","A radio station"],c:0,cat:"MIND",tier:"documented"},
  {q:"What does it mean to be persuaded?",a:["Convinced to think or do something","Forced to sleep","Given money","Lost in a building"],c:0,cat:"MIND",tier:"documented"}
];
